# Generated by Django 5.1.3 on 2026-04-08 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiliereOrientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filiere', models.CharField(max_length=20, unique=True)),
                ('nom_filiere', models.CharField(max_length=200)),
                ('type_profil_filiere', models.CharField(choices=[('bachelier', 'Bachelier'), ('tous', 'Tous')], default='bachelier', max_length=15)),
                ('niveau_minimum', models.CharField(blank=True, max_length=50, null=True)),
                ('duree_etudes', models.CharField(blank=True, max_length=100, null=True)),
                ('description_filiere', models.TextField(blank=True, null=True)),
                ('debouches', models.TextField(blank=True, null=True)),
                ('conditions_acces', models.TextField(blank=True, null=True)),
                ('competences_requises', models.TextField(blank=True, null=True)),
                ('actif_filiere', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'filiere_orientation',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100, unique=True)),
                ('categorie_matiere', models.CharField(choices=[('litteraire', 'Littéraire'), ('scientifique', 'Scientifique'), ('linguistique', 'Linguistique'), ('artistique', 'Artistique'), ('sportive', 'Sportive'), ('generale', 'Générale')], max_length=20)),
                ('coeff_default', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_util', models.EmailField(max_length=150, unique=True)),
                ('pwd_util', models.CharField(max_length=255)),
                ('nom_util', models.CharField(max_length=100)),
                ('prenom_util', models.CharField(max_length=100)),
                ('tel_util', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_compatibilite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('niveau_reco', models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Bonne', 'Bonne'), ('Excellente', 'Excellente')], max_length=10)),
                ('details_analyse', models.JSONField(blank=True, null=True)),
                ('date_reco', models.DateTimeField(auto_now_add=True)),
                ('est_consultee', models.BooleanField(default=False)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='orientation.filiereorientation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='orientation.utilisateur')),
            ],
            options={
                'db_table': 'recommandation',
            },
        ),
        migrations.CreateModel(
            name='ProfilBachelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_bac', models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('A2', 'A2'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('G1', 'G1'), ('G2', 'G2'), ('TI', 'TI')], max_length=5)),
                ('mention_bac', models.CharField(choices=[('Passable', 'Passable'), ('Assez bien', 'Assez bien'), ('Bien', 'Bien'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=15)),
                ('moyenne_bac', models.DecimalField(decimal_places=2, max_digits=4)),
                ('annee_bac', models.PositiveIntegerField()),
                ('etablissement_bac', models.CharField(blank=True, max_length=200, null=True)),
                ('aspirations_bac', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_bachelier', to='orientation.utilisateur')),
            ],
            options={
                'db_table': 'profil_bachelier',
            },
        ),
        migrations.CreateModel(
            name='PonderationMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff_importance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderations', to='orientation.filiereorientation')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponderations', to='orientation.matiere')),
            ],
            options={
                'db_table': 'ponderation_matiere',
                'unique_together': {('filiere', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='NoteBachelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_bac', models.DecimalField(decimal_places=2, max_digits=4)),
                ('coefficient_bac', models.DecimalField(decimal_places=1, max_digits=3)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='orientation.matiere')),
                ('profil_bachelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orientation.profilbachelier')),
            ],
            options={
                'db_table': 'notes_bachelier',
                'unique_together': {('profil_bachelier', 'matiere')},
            },
        ),
    ]
