# Generated by Django 5.1.3 on 2026-04-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(default='temp_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
