# Generated by Django 5.1.3 on 2026-04-22 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0002_utilisateur_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebachelier',
            name='note_bac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='profilbachelier',
            name='mention_bac',
            field=models.CharField(blank=True, choices=[('Passable', 'Passable'), ('Assez bien', 'Assez bien'), ('Bien', 'Bien'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profilbachelier',
            name='serie_bac',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('G1', 'G1'), ('G2', 'G2'), ('TI', 'TI')], max_length=5),
        ),
        migrations.CreateModel(
            name='NoteTrimestrielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_trimestrielles', to='orientation.matiere')),
                ('profil_bachelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_trimestrielles', to='orientation.profilbachelier')),
            ],
            options={
                'db_table': 'note_trimestrielle',
                'unique_together': {('profil_bachelier', 'matiere', 'trimestre')},
            },
        ),
    ]
