# Generated by Django 5.1.3 on 2026-05-04 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0003_alter_notebachelier_note_bac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_concours', models.CharField(max_length=30, unique=True)),
                ('nom_concours', models.CharField(max_length=200)),
                ('etablissement', models.CharField(choices=[('INPHB', 'INP-HB Yamoussoukro'), ('ESATIC', 'ESATIC Abidjan')], max_length=10)),
                ('ecole', models.CharField(blank=True, max_length=100, null=True)),
                ('filiere_cible', models.CharField(max_length=200)),
                ('type_acces', models.CharField(choices=[('ecrit', 'Concours écrit'), ('dossier', 'Étude de dossier'), ('mixte', 'Écrit + Dossier')], max_length=10)),
                ('series_requises', models.CharField(max_length=100)),
                ('moyenne_min', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('note_maths_min', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('note_physique_min', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('duree_formation', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('debouches', models.TextField(blank=True, null=True)),
                ('documents_requis', models.TextField(blank=True, null=True)),
                ('frais_inscription', models.CharField(blank=True, max_length=50, null=True)),
                ('age_max', models.IntegerField(default=25)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'concours',
            },
        ),
        migrations.CreateModel(
            name='RecommandationConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_admission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('niveau_chance', models.CharField(choices=[('Faible', 'Faible'), ('Possible', 'Possible'), ('Bonne', 'Bonne'), ('Excellente', 'Excellente')], max_length=10)),
                ('details', models.JSONField(blank=True, null=True)),
                ('date_reco', models.DateTimeField(auto_now_add=True)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='orientation.concours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations_concours', to='orientation.utilisateur')),
            ],
            options={
                'db_table': 'recommandation_concours',
            },
        ),
        migrations.CreateModel(
            name='MoyenneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('2nde', 'Seconde'), ('1ere', 'Première')], max_length=5)),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='orientation.matiere')),
                ('profil_bachelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='orientation.profilbachelier')),
            ],
            options={
                'db_table': 'moyenne_bulletin',
                'unique_together': {('profil_bachelier', 'matiere', 'classe')},
            },
        ),
    ]
