# Generated by Django 5.1.3 on 2026-05-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0004_concours_recommandationconcours_moyennebulletin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concours',
            name='frais_inscription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
