# Generated by Django 5.1.3 on 2026-05-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0005_alter_concours_frais_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concours',
            name='series_requises',
            field=models.CharField(max_length=200),
        ),
    ]
