# Generated by Django 5.1.3 on 2026-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0006_alter_concours_series_requises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concours',
            name='etablissement',
            field=models.CharField(choices=[('INPHB', 'INP-HB Yamoussoukro'), ('ESATIC', 'ESATIC Abidjan'), ('ETAT', "Fonction Publique — État de Côte d'Ivoire")], max_length=10),
        ),
    ]
