# Generated by Django 4.2.30 on 2026-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0008_moyennebulletin_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='choix_final',
            field=models.BooleanField(default=False, help_text='Filière choisie par le bachelier comme choix définitif'),
        ),
    ]
